local Config = {
	GameName = "Eclipsis",
	Debug = true,
	ShowWelcomeNotification = true,
	EnableBytecodeViewer = true,
	RemoteRepoOwner = "PuzzleFP",
	RemoteRepoName = "Dart",
	RemoteRepoRef = "main",
	RemoteModulesPath = "client/Modules",
	RemoteRawBaseUrl = "https://raw.githubusercontent.com/PuzzleFP/Dart/main/",
	RemoteModulesBaseUrl = "https://raw.githubusercontent.com/PuzzleFP/Dart/main/client/Modules/",
	RemoteMainUrl = "https://raw.githubusercontent.com/PuzzleFP/Dart/main/client/main.lua",
	DefaultTab = "main",
	DefaultBytecodeSourceMode = "script",
	DefaultBytecodeViewMode = "code",
	DefaultScriptPath = "",
	DefaultBytecodeFilePath = "C:\\Users\\Marin\\Downloads\\Test.txt",
	DefaultBytecodeInputFormat = "binary",
	ShowRawOpcodes = true,
	IntelligenceThreatRange = 350,
	IntelligenceThreatInterval = 0.35,
	IntelligenceCriticalRange = 60,
	IntelligenceTurretRange = 160,
	IntelligenceTurretNearMultiplier = 1.25,
	IntelligenceTurretLineOfSightDegrees = 42,
	IntelligenceLowHealthPercent = 0.35,
	ActionHandlers = {},
}

return table.freeze(Config)
